spring:
  cloud:
    discovery:
      enabled: true
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 8086

jwt:
  secret: ${JWT_SECRET}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
