name: IR pipeline-frontend
on:
  push:
    branches:
      - ci/pipeline
    paths:
      - IntelligentRecruitment-UI/**
      - .github/workflows/pipeline-frontend.yml

jobs:
  build-image:
    runs-on: ubuntu-latest
    name: Build Docker image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to dockerhub
        run: |
          cd IntelligentRecruitment-UI
          docker build -t ir-ui:latest .
          docker push ir-ui:latest

  deploy:
    name: Deploy frontend
    runs-on: ubuntu-latest
    needs: [build-image]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy frontend
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem -o StrictHostKeyChecking=no "${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}" "mkdir -p ci-cd"
          scp -i private_key.pem -o StrictHostKeyChecking=no IntelligentRecruitment_microservice/docker-compose.yml "${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}:ci-cd/docker-compose.yml"
          ssh -i private_key.pem -o StrictHostKeyChecking=no "${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }}" "cd ci-cd && docker compose pull && docker compose up -d"
          rm -f private_key.pem
          

